### ISSUE TITLE
Use util-map.json to manage the js-dependencies of foundation components

### ISSUE THREAD

**Issue by core77** [core77/jekyll-foundation#1]
How can we use [util-map.json](https://github.com/zurb/foundation-sites/blob/develop/lib/util-map.json) smart in the gulpfile / gulp workflow?

**Comment by captaincoffee** [comment]
Is this why several of the js files are not loading properly? Particularly to do with different menus.

**Comment by core77** [comment]
No, I don't think so. The Foundation for Sites JavaScript files aren't included by default.

This gives you the ability to only include files (js/scss) which are required for your project.

If you want to use let's say the top-bar component, you have to do the following things:
1. uncomment the include for foundation-top-bar in /assets/scss/foundation/_foundation.scss 
2. uncomment the required JavaScript files for foundation-top-bar in gulpfile.js
3. restart gulp because you edited the gulpfile (`ctrl + c`and `gulp`)

I've just upgraded to Foundation for Sites 6.0.5 and saw they dropped the util-map.json file.

I'll keep an eye on this, because for this moment I don't know for sure which components needs which JavaScript files.

For testing purposes you can uncomment all the Sass imports and JavaScript files. Then all the components on the kitchen sink page (in your local project) should work!

Feel free to ask again if things don't work.

**Comment by captaincoffee** [comment]
I truly appreciate the help.

**Comment by johndnixon** [comment]
My issue may be me being a noob with jekyll, but when I try and use jekyll serve the assets folder doesn't get compiled into the _site folder. Not sure if I'm doing something wrong or if its a possible issue.

**Comment by core77** [comment]
@johndnixon You have to use the `gulp` command for building your site and the assets.
That's because we use a gulp workflow here. You can say: Gulp tells jekyll when to build the site. You don't have to run `jekyll build` or `jekyll serve` yourself.

To avoid conflicts the compiling of sass is not activated in jekyll (there's no sass_dir in _config.yml). 
If you want to use the jekyll functionality you can take a look at the [jekyll docs](http://jekyllrb.com/docs/assets/#sassscss).

The reason for me to use gulp was to be able to control the build process with concatenating and minifying the assets and (thanks to browsersync and xip.io) to be able to easily access my local site from smartphones or tablets.

**Comment by captaincoffee** [comment]
For development, I have uncommented almost everything in the scss and gulp.js files. There seems to be no change in functionality. Any ideas are appreciated.

**Comment by core77** [comment]
Take a look at the gulpfile.js and check if you have the latest version. The first version had some performance issues...

**Comment by core77** [comment]
Discarding this idea.
