### ISSUE TITLE
Updating Foundation

### ISSUE THREAD

**Issue by captaincoffee** [core77/jekyll-foundation#2]
What is the proper way to safely update Foundation 6 within the repo?

**Comment by core77** [comment]
That's why we use bower (www.bower.io)!

1. go to bower.json and change the version number of foundation for sites (to 6.0.5)
2. in your terminal execute 'bower update'

That's it! The next time you start `gulp`the app.css will be build from the sources of foundation for sites 6.0.5.

**Comment by captaincoffee** [comment]
Thanks
