### ISSUE TITLE
jekyll-paginate and jekyll-sitemap

### ISSUE THREAD

**Issue by dianafaye17** [core77/jekyll-foundation#3]
You have to gem install jekyll-paginate and jekyll-sitemap manually before doing bundler install.

**Comment by core77** [comment]
When I run 'bundle install' bundler installs jekyll-paginate and jekyll-sitemap for me. So I can't confirm this (on Mac OS El Capitan and Linux Mint 17.3)

Someone else here, who has to install the gems before running 'bundle install'?

**Comment by grosenbaum** [comment]
Everything works fine for me following `README.md` on Ubuntu Trusty
