### ISSUE TITLE
gulp / npm start error

### ISSUE THREAD

**Issue by GrantMoran** [core77/jekyll-foundation#30]
Hello, I thought I was receiving the following error only when uncommenting js components in the config file, however this error throws even after somehow getting a successful npm start to launch normally. The error is constant, but sometimes running npm start is successful. I've included two npm debug logs before and after updating node. I had another error though during the node update in which is stated jekyll_foundation couldn't be upgraded. New to debugging issues like this but really want to use this build setup. I have already learned so much just from playing with it so far. Thanks in advance.

`stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ENOENT: no such file or directory, stat '/Users/grantmoran/Documents/jekyll-foundation-test/_site/assets/css/app.css'
    at Error (native)` 

Older version node error:

`0 info it worked if it ends with ok
1 verbose cli [ '/Users/username/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/username/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.5.1
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jekyll-foundation@0.2.1~prestart: jekyll-foundation@0.2.1
6 silly lifecycle jekyll-foundation@0.2.1~prestart: no script for prestart, continuing
7 info lifecycle jekyll-foundation@0.2.1~start: jekyll-foundation@0.2.1
8 verbose lifecycle jekyll-foundation@0.2.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle jekyll-foundation@0.2.1~start: PATH: /Users/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/Documents/jekyll-foundation-test/node_modules/.bin:/Users/username/.rvm/gems/ruby-2.2.1/bin:/Users/username/.rvm/gems/ruby-2.2.1@global/bin:/Users/username/.rvm/rubies/ruby-2.2.1/bin:/Users/username/.nvm/versions/node/v5.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/username/.rvm/bin
10 verbose lifecycle jekyll-foundation@0.2.1~start: CWD: /Users/username/Documents/jekyll-foundation-test
11 silly lifecycle jekyll-foundation@0.2.1~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle jekyll-foundation@0.2.1~start: Returned: code: 1  signal: null
13 info lifecycle jekyll-foundation@0.2.1~start: Failed to exec start script
14 verbose stack Error: jekyll-foundation@0.2.1 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/username/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid jekyll-foundation@0.2.1
16 verbose cwd /Users/username/Documents/jekyll-foundation-test
17 error Darwin 14.5.0
18 error argv "/Users/username/.nvm/versions/node/v5.0.0/bin/node" "/Users/username/.nvm/versions/node/v5.0.0/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.5.1
21 error code ELIFECYCLE
22 error jekyll-foundation@0.2.1 start: `gulp`
22 error Exit status 1
23 error Failed at the jekyll-foundation@0.2.1 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jekyll-foundation package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jekyll-foundation
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jekyll-foundation
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Updated node version error:

`0 info it worked if it ends with ok
1 verbose cli [ '/Users/username/.nvm/versions/node/v5.7.1/bin/node',
1 verbose cli   '/Users/username/.nvm/versions/node/v5.7.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jekyll-foundation@0.2.1~prestart: jekyll-foundation@0.2.1
6 silly lifecycle jekyll-foundation@0.2.1~prestart: no script for prestart, continuing
7 info lifecycle jekyll-foundation@0.2.1~start: jekyll-foundation@0.2.1
8 verbose lifecycle jekyll-foundation@0.2.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle jekyll-foundation@0.2.1~start: PATH: /Users/username/.nvm/versions/node/v5.7.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/Documents/jekyll-foundation-test/node_modules/.bin:/Users/username/.nvm/versions/node/v5.7.1/bin:/Users/username/.rvm/gems/ruby-2.2.1/bin:/Users/username/.rvm/gems/ruby-2.2.1@global/bin:/Users/username/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/username/.rvm/bin
10 verbose lifecycle jekyll-foundation@0.2.1~start: CWD: /Users/username/Documents/jekyll-foundation-test
11 silly lifecycle jekyll-foundation@0.2.1~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle jekyll-foundation@0.2.1~start: Returned: code: 1  signal: null
13 info lifecycle jekyll-foundation@0.2.1~start: Failed to exec start script
14 verbose stack Error: jekyll-foundation@0.2.1 start: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/username/.nvm/versions/node/v5.7.1/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/username/.nvm/versions/node/v5.7.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid jekyll-foundation@0.2.1
16 verbose cwd /Users/username/Documents/jekyll-foundation-test
17 error Darwin 14.5.0
18 error argv "/Users/username/.nvm/versions/node/v5.7.1/bin/node" "/Users/username/.nvm/versions/node/v5.7.1/bin/npm" "start"
19 error node v5.7.1
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error jekyll-foundation@0.2.1 start: `gulp`
22 error Exit status 1
23 error Failed at the jekyll-foundation@0.2.1 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jekyll-foundation package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jekyll-foundation
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jekyll-foundation
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by core77** [comment]
How did you install Node.js? Via the installer on their website? Or with homebrew?

What about 'npm run build'? Does that work?

**Comment by sackwort** [comment]
I'm getting this same error. I'm running this on Linux Mint via RVM.

I noticed that the Gemfile with jekyll-foundation states Ruby 2.2.3 as the Ruby requirement, but I've tried using jekyll-foundation with 2.2.3 and 2.2.1 and got the same error with both. I've attached my npm-debug.log, which, I think, is pretty much the same as the opening post.
[npm-debug.txt](https://github.com/core77/jekyll-foundation/files/183014/npm-debug.txt)

**Comment by core77** [comment]
Until now I didn't find the culprit. 

On my machines with Mac OS El Capitan and a elementary OS virtual machine it works...

I was thinking about using jekyll only for html generation. That means the assets will completely be handled by gulp tasks. Hope thats will fix the issue.

**Comment by sackwort** [comment]
Would the Node.js version have any effect? I'm using 5.9.0.

**Comment by core77** [comment]
Node 5.x should work because it passes the Travis builds. You can see details here:
https://travis-ci.org/core77/jekyll-foundation

Today i was working on using jekyll only for HTML files. I just committed the 'jekyll/html-only' branch so you guys can test it.

Known issue:
When running 'npm run build' the assets folder is written twice to _site. One version named 'assets' and the other named '_assets'. The culprit here is the revision task and the rev-manifest.json. This is a TODO...

**Comment by sackwort** [comment]
I just tried the 'jekyll/html-only' branch and, unfortunately, got the same error. I wish I could offer more help, but I wouldn't know where to start!

**Comment by sackwort** [comment]
Today I removed my system Node.js and installed Node Version Manager (github.com/creationix/nvm). Then I installed jekyll-foundation and it's now working perfectly.

**Comment by core77** [comment]
@sackwort Nice. Thanks for the feedback!

On Mac OS i always use the installer from nodejs.org. On my 'elementary OS' virtual machine i go this way: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by grshane** [comment]
I am having the same issue. Node.js downloaded from nodejs.org. OS X El Capitan. 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/grshane/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.8.5
3 info using node@v5.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jekyll-foundation@0.3.0~prebuild: jekyll-foundation@0.3.0
6 silly lifecycle jekyll-foundation@0.3.0~prebuild: no script for prebuild, continuing
7 info lifecycle jekyll-foundation@0.3.0~build: jekyll-foundation@0.3.0
8 verbose lifecycle jekyll-foundation@0.3.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle jekyll-foundation@0.3.0~build: PATH: /Users/grshane/.npm-global/lib/node_modules/npm/bin/node-gyp-bin:/development/htdocs/fyds/node_modules/.bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/Users/grshane/npm-global/bin:/Users/grshane/.rvm/gems/ruby-2.2.2/bin:/Users/grshane/.rvm/gems/ruby-2.2.2@global/bin:/Users/grshane/.rvm/rubies/ruby-2.2.2/bin:/Users/grshane/.composer/vendor/bin:/opt/local/bin:/opt/local/sbin:/usr/local/autoconf/bin:/opt/local/bin:/opt/local/sbin:/Users/grshane/.npm-global/bin:/Applications/MAMP/Library/bin/:/Users/grshane/.composer/vendor/bin:/Applications/MAMP/bin/php/php5.6.7/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/Users/grshane/.rvm/bin:/Users/grshane/.rvm/bin:/Users/grshane/.rvm/gems/ruby-2.2.2/bin/compass:/Users/grshane/.rvm/bin
10 verbose lifecycle jekyll-foundation@0.3.0~build: CWD: /development/htdocs/fyds
11 silly lifecycle jekyll-foundation@0.3.0~build: Args: [ '-c', 'gulp build --production' ]
12 silly lifecycle jekyll-foundation@0.3.0~build: Returned: code: 1  signal: null
13 info lifecycle jekyll-foundation@0.3.0~build: Failed to exec build script
14 verbose stack Error: jekyll-foundation@0.3.0 build: `gulp build --production`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/grshane/.npm-global/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/grshane/.npm-global/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid jekyll-foundation@0.3.0
16 verbose cwd /development/htdocs/fyds
17 error Darwin 15.3.0
18 error argv "/usr/local/bin/node" "/Users/grshane/.npm-global/bin/npm" "run" "build"
19 error node v5.10.0
20 error npm  v3.8.5
21 error code ELIFECYCLE
22 error jekyll-foundation@0.3.0 build: `gulp build --production`
22 error Exit status 1
23 error Failed at the jekyll-foundation@0.3.0 build script 'gulp build --production'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jekyll-foundation package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build --production
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jekyll-foundation
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jekyll-foundation
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Moobz** [comment]
Hi Grant Moran. 

Please reply to my email / Skype messages, You have stolen from me and I would like an explanation.

Regars :)
