### ISSUE TITLE
Settings don't take effect when using Foundation v 6.2.1

### ISSUE THREAD

**Issue by core77** [core77/jekyll-foundation#34]
if I change the $primary-color (or any other color) in _settings.scss, it remains the same default blue/grey/etc. If I move the settings file down the page on foundation.scss, I can get my custom css (in theme.scss) to show my edited value, but still not the links, buttons, etc.
No errors.
I should note that if I change other values in _settings.scss, like font sizes, those changes take effect.

Thanks to @daneclarkcollins for reporting this. Stumbled on this error, too.

Edit: This doesn't happen, when using Foundation 6.0.6

**Comment by rogercoathup** [comment]
Looks like you have the old style settings file in  /assets/scss/foundation/_settings.scss

The 6.2 settings file is different -- in particular it uses a color palette for things like $primary-color

**Comment by core77** [comment]
What's your opinion about this:

We completely empty the /assets/scss/foundation/_settings.scss file.

When we want to override Foundation default values we copy the variable(s) 
from 
`/assets/vendor/foundation-sites/scss/settings/_settings.scss`
to 
`/assets/scss/foundation/_settings.scss` 
and change their value(s)

This way we would avoid the /assets/scss/foundation/_settings.scss to become outdated.

**Comment by rogercoathup** [comment]
Yes, I think that makes sense.

It's always an issue managing the settings file through Foundation updates, and requires a fair bit of manual intervention, i.e. you want the latest settings file structure / defaults, but you don't want to lose your site specific changes.

**Comment by rogercoathup** [comment]
Unfortunately this fix doesn't work -- if you copy in the new settings file to /assets/scss/foundation/_settings.scss, it throws an error because of the relative path to other imports:

Error in plugin 'sass'
Message:
    assets/scss/foundation/_settings.scss
Error: File to import not found or unreadable: util/util
       Parent style sheet: /Users/roger/Development/21/jekyll-foundation/assets/scss/foundation/_settings.scss
        on line 43 of assets/scss/foundation/_settings.scss
>> @import 'util/util';
   ^

**Comment by core77** [comment]
I stumbled on that error, too, when i copied the whole settings file. 

I would recommend to only copy the variables which you want to change.
