### ISSUE TITLE
Foundation's JS is not working.

### ISSUE THREAD

**Issue by indrakaw** [core77/jekyll-foundation#37]
I follow the wiki then served it locally by run `npm start`, but it won't initialize Foundation. Why?

I though there was a problem on the local machine, so I deployed it on Netlify on the following address: http://inspector-zebra-64764.netlify.com/kitchen-sink/ [(Source Repo)](https://github.com/indrakaw/jekyll-foundation/)

The result is the same.

**Comment by core77** [comment]
Did you uncomment the component's JS in [/gulp/config.yml](https://github.com/core77/jekyll-foundation/wiki/Getting-started#foundation-for-sites-components)?

**Comment by indrakaw** [comment]
Wow. It works! SUPER!
