### ISSUE TITLE
Not syncing with GitHub Pages

### ISSUE THREAD

**Issue by cmarchena** [core77/jekyll-foundation#39]
I followed all your instructions, even though it works in local servers, once you upload to GH, an error is occurring.
Would you please check? Maybe I'm doing something wrong.
Two GitHub Pages projects that you can check to understand better the error:
[Socama](https://socama.github.io/boqueteadventures/)
[Cmarchena](https://cmarchena.github.io/jekyll-foundation/)
Kind regards!

**Comment by core77** [comment]
Hi. Sorry, but this package is meant to build your Site on your local machine. Not to deploy to GitHub Pages.
