### ISSUE TITLE
Foundation.MediaQuery undefined in all.js

### ISSUE THREAD

**Issue by dianafaye17** [core77/jekyll-foundation#4]
Foundation.MediaQuery is undefined in all.js. 
It gives a Chrome console error message that reads:  
Uncaught TypeError: Cannot read property '_init' of undefinedfoundation @ all.js:5(anonymous function) @ all.js:5

**Comment by core77** [comment]
That's right. 

You have to uncomment the JavaScript you need for your project in PATHS.javascript in the gulpfile. Then the error doesn't occure.

**Comment by dianafaye17** [comment]
Ah, thank you so much.
