### ISSUE TITLE
app.js (Foundation JS file) not loading properly 

### ISSUE THREAD

**Issue by justinmarkfarrugia** [core77/jekyll-foundation#46]
I've been uncommenting the files as mentioned in the other issue that was raised but for some reason the I'm still getting a Reference Error saying that `$ is not defined` which I'm guessing is jQuery not being properly loaded or called within the project.

<img width="876" alt="screen shot 2017-01-26 at 11 01 50 pm" src="https://cloud.githubusercontent.com/assets/13674072/22352216/83f36734-e41b-11e6-90b7-66f93548327b.png">

**Let me know if I haven't described the issue well enough to be addressed.** 

![screen shot 2017-01-26 at 11 06 13 pm](https://cloud.githubusercontent.com/assets/13674072/22352369/1e8510f4-e41c-11e6-9dfb-a281ade1ffd5.png)

From the first image I guess you can tell that, I'm not quite sure my CSS is being loaded up properly either. One thing I've changed from the project since following all setup instructions is that I've merged the bower-components folder contents into the vendor folder. Maybe this might have triggered the issue?

**Comment by core77** [comment]
Can't confirm this, sorry. 

I clone the repo, ran ```bundle install```, ```npm install```and ```bower install```. Afer starting the project with ```npm start```there were no errors in my console...

**Comment by justinmarkfarrugia** [comment]
Hey so I've cloned the repo, and ran `make install` which basically did the same thing as you've mentioned above and don't have any console errors, so that issue's been addressed. One thing though is that I'm still getting the same result when looking through the kitchen sink. 

If you would be so kind, would you mind if you show me a screenshot of what I'm meant to be seeing once I access the local URL after I run `npm start`

Reason as to why I'm asking for a screenshot is that perhaps Foundation isn't loading properly (which I've tried to address by commenting and uncommenting as you've suggested).

**Comment by core77** [comment]
Sent!
