### ISSUE TITLE
including unique assets without concantenation

### ISSUE THREAD

**Issue by jshwlkr** [core77/jekyll-foundation#59]
I'm trying to include per-post js/css/scss via the front matter (like so https://mattgemmell.com/page-specific-assets-with-jekyll/) and I'm not sure the best method to keep the files from being compiled into the app.css and all.js but still have them copied into the _site directory. I'm assuming it's not by messing around with how the vendor folder is handled. (Even better if I could still get any unique assets compiled and minified.)

**Comment by core77** [comment]
What if you use a new folder called `assets/css_unique` for this?

For SCSS compiling I would add a separate gulp task to handle these files.

**Comment by jshwlkr** [comment]
Ah! Yes. This approximates what I need. thanks.
