### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by core77** [core77/jekyll-foundation#7]
You can [![join the chat at https://gitter.im/core77/jekyll-foundation](https://badges.gitter.im/core77/jekyll-foundation.svg)](https://gitter.im/core77/jekyll-foundation) (login is easy there with your GitHub account).

If something doesn't work like expected and you think you found a bug, feel free to create a `new issue`.

**Comment by shoshorov** [comment]
`npm start` crashes on `jekyll-build` task - Windows 10. It seems that `child_process.spawn` doesn't work very well on Windows. I replaced it with `cross-spawn` and now I'm able to bluid the site.

**Comment by core77** [comment]
@shoshorov Please make a pull request! Well done!
